### PR TITLE
Change desktop CLR appbase to KRE bin folder and allow ngen'd image to load

### PR DESCRIPTION
**Pull request by shhsu**
Tested, fusion log entry shows ngen image is loaded

```
*** Assembly Binder Log Entry  (2/4/2015 @ 3:07:37 PM) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\IIS Express\iisexpress.exe
--- A detailed error log follows. 

*** Assembly Binder Log Entry  (2/4/2015 @ 4:08:25 PM) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\IIS Express\iisexpress.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.CodeAnalysis.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/temp/BasicMVC/approot/packages/kre-clr-win-x86.1.0.0-beta4-11008/bin
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\99e40170-_LM_W3SVC_1_ROOT
LOG: AppName = 99e40170
Calling assembly : Microsoft.Framework.Runtime.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.

...

WRN: Timestamp of the IL assembly does not match record in .aux file. Loading IL to compare signature.
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: [Level 1]Start validating IL dependency System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency Microsoft.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
WRN: Timestamp of the IL assembly does not match record in .aux file. Loading IL to compare signature.
LOG: [Level 1]Start validating IL dependency System.Collections.Immutable, Version=1.1.33.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
WRN: Timestamp of the IL assembly does not match record in .aux file. Loading IL to compare signature.
LOG: [Level 1]Start validating IL dependency System.Globalization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: [Level 1]Start validating IL dependency System.Reflection.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Linq.Expressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Reflection.Metadata, Version=1.0.18.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
WRN: Timestamp of the IL assembly does not match record in .aux file. Loading IL to compare signature.
LOG: [Level 1]Start validating IL dependency System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Collections.Concurrent, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: [Level 1]Start validating IL dependency System.Diagnostics.Debug, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Threading.Tasks.Parallel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Threading, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Xml.XDocument, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: [Level 1]Start validating IL dependency System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
LOG: [Level 1]Start validating IL dependency System.Xml.ReaderWriter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Diagnostics.Tools, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Text.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Dynamic.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
LOG: [Level 1]Start validating IL dependency System.Text.Encoding.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Native image has correct version information.
LOG: Validation of dependencies succeeded.
LOG: Bind to native image succeeded.
Attempting to use native image C:\Windows\assembly\NativeImages_v4.0.30319_32\Microsoft.C1d3c2215#\5e314fc8d709284acd6c1f20f77de43c\Microsoft.CodeAnalysis.CSharp.ni.dll.
Native image successfully used.
```

### CODE REVIEW

**Comment by shhsu** [comment]
related to https://github.com/aspnet/dotnetsdk/pull/152

**Comment by shhsu** [comment]
Note that the above logs
WRN: Timestamp of the IL assembly does not match record in .aux file. Loading IL to compare signature.
Would not exist in production because we would both ngen install and load from KRE_HOME.

**Comment by davidfowl** [comment]
@shhsu will this happen during dev as well?

/cc @jkotas @jhawk42 

Do you guys know why this would happen?

**Comment by shhsu** [comment]
Let me clarify:

We are seeing these warning because when I kvm install, the corrosponding ngen install is called on the Roslyn libraries in KRE_HOME. (i. e. %USERPROFILE%\.k\runtimes\...)

However when I am testing the feature I am using my own build of KRE. The ngen images still loads because this build of KRE (i.e. %MYAPP%\approot\packages\...) has the same Roslyn dll as the one installed previously. However, because the timestamp is different we see these warnings.

In any production scenario including dev or production, we won't see these warnings because things always load from KRE_HOME

**Comment by davidfowl** [comment]
Ah hah!

**Comment by davidfowl** [comment]
One issue with this change is the fact that we won't be able to load roslyn from the application as an override (if we choose to support that again). We need to see if that scenario still works with this change.

**Comment by jhawk42** [comment]
@davidfowl are you ok with @shhsu making this change in XKE? If so, lets move ahead with it.

**Comment by shhsu** [comment]
@davidfowl 

How would i test the issue in concern? Or who should I contact?

**Comment by jhawk42** [comment]
@shhsu I spoke with @davidfowl yesterday and he is ok with the change. In the future we may need to add an opt out switch.

**Pull request merged**
