### PR TITLE
Install global

### PR DESCRIPTION
**Pull request by victorhurdugaci**
Change: 
- The install global command. Named temporary `install-g`.
- Tests for `install-g`
- Moved feed options in a centralized place

Will address uninstall in a different PR.

Please review: @davidfowl @loudej

### CODE REVIEW

**Comment by borgdylan** [comment]
Will bash scripts be made like it is the case with kpm bundle?

**Comment by victorhurdugaci** [comment]
@borgdylan yes but for now (as in the code checked in so far) is only cmd.

**Comment by victorhurdugaci** [comment]
I said that uninstall with go in a later iteration but I have a working prototype of it and I checked in

Fixes https://github.com/aspnet/XRE/issues/1140

**Comment by victorhurdugaci** [comment]
Closing for now because I have more changes to add

**Pull request closed without merging**
