### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by ellismg**
The "Firmware" methods living in module.cpp for the coreclr native
loader appeared to be unused by the klr bootstrapper. I have removed
them and updated the call in klr.cpp to not use the firmware name.

I was able to use klr after building with this change to run hello
world against coreclr, so I don't believe this stuff is needed
anymore.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@ellismg__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Matt Ellis). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by davidfowl** [comment]
LGTM

**Comment by ellismg** [comment]
@davidfowl FYI, I'm not a collaborator on this repository (maybe that's a good thing for the future for me?) so I won't be able to merge this myself.  Thanks for taking a look.

**Comment by troydai** [comment]
@davidfowl want me to merge this change?

**Comment by davidfowl** [comment]
I'll merge it in

**Pull request merged**
